version: '3'

services:
  library-api:
    container_name: library-api
    build: .
    ports:
      - "8080:8080"
    networks:
      - library-api-network
    depends_on:
      - library-api-redis
      - library-api-db

  library-api-db:
    image: mysql:8.0.25
    container_name: library-api-db
    ports:
      - "3306:3306"
    volumes:
      - library_api_mysql:/var/lib/mysql
      - library_api_mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - library-api-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=library-api-redis
    ports:
      - "1004:8081"
    networks:
      - library-api-network
    depends_on:
      - library-api-redis

  library-api-redis:
    image: redis:alpine
    container_name: library-api-redis
    ports:
      - "6379:6379"
    volumes:
      - library_api_redis:/data
    networks:
      - library-api-network

  library-api-prometheus:
    image: prom/prometheus:v2.36.1
    container_name: library-api-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - library-api-network

  library-api-grafana:
    image: grafana/grafana:9.0.0
    container_name: library-api-grafana
    ports:
      - "3000:3000"
    env_file:
      - ./grafana.env
    networks:
      - library-api-network
    depends_on:
      - library-api

networks:
  library-api-network:
    driver: bridge

volumes:
  library_api_mysql:
    driver: local
  library_api_redis:
