version: '3'

services:
  library-api:
    container_name: library-api
    build: .
    ports:
      - "8080:8080"
    networks:
      - library-api-network
    depends_on:
      - library-api-redis
      - library-api-db

  library-api-db:
    image: mysql:8.0.25
    container_name: library-api-db
    ports:
      - "3306:3306"
    volumes:
      - ./.database/data:/var/lib/mysql
      - ./.database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=library_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - library-api-network

  library-api-redis:
    image: redis:alpine
    container_name: library-api-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.database/redis:/data
    networks:
      - library-api-network

networks:
  library-api-network:
    driver: bridge
