apiVersion: v1
kind: Namespace
metadata:
  name: learning-spring
spec:
  finalizers:
    - kubernetes

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-mysql
  name: spring-mysql
  namespace: learning-spring
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3306
    nodePort: 32222
    protocol: TCP
    targetPort: 3306
  type: NodePort
  selector:
    app: spring-mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-mysql
  name: spring-mysql
  namespace: learning-spring
spec:
  selector:
    matchLabels:
      app: spring-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
      - image: mysql:8.0.31
        name: spring-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: library
        ports:
        - containerPort: 3306
          name: spring-mysql
        volumeMounts:
        - name: spring-mysql-persist-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: spring-mysql-persist-storage
        persistentVolumeClaim:
          claimName: spring-mysql-pv-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-mysql-pv-claim
  namespace: learning-spring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-mysql-pv-volume
  labels:
    type: local
  namespace: learning-spring
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

